import 'bootstrap/dist/css/bootstrap.min.css';
import "./globals.css";
import Header from "./components/Header/page";
import AppContext from '@/AppContent/context';
import Sidebar from './components/Sidebar/Page';

export const metadata = {
  title: "Youtube App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <section className="main">
        <AppContext>
          <Header/>
          <div className='wrapper d-flex'>
    
              <Sidebar/>
              {children}
            
          </div>
        </AppContext>
        </section>
      </body>
    </html>
  );
}
